name: almostjaded
favicon: null
layout_spectrum: 0.6544536058790982
typography_spectrum: 0.8354320963844657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7883923242334276
  lightness: 0.5037443635519594
  saturation: 0.03166956012137234
  rhythmicContrast: 0.6999609910417348
purpose: []
